# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  libraryapimysql:
    image: libraryapimysql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5135:5135
